// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package services

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID    int32
	UserName  string
	UserEmail string
	FirstName pgtype.Text
	LastName  pgtype.Text
	CreateAt  pgtype.Timestamp
	DeleteAt  pgtype.Timestamp
	Active    pgtype.Bool
}
