// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package connect

import (
	"github.com/jmoiron/sqlx"
	"gogofi/internal/handler"
	"gogofi/internal/repo"
)

// Injectors from wire.go:

func InitializeApp(db *sqlx.DB) *handler.UserHandler {
	repoRepo := repo.NewRepo(db)
	userHandler := handler.NewUserHandler(repoRepo)
	return userHandler
}
