// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package connect

import (
	"gogofi/internal/controller"
	"gogofi/internal/database/services"
)

// Injectors from wire.go:

func InitializeApp(db services.DBTX) *controller.UserController {
	queries := services.New(db)
	userController := controller.NewUserController(queries)
	return userController
}
